// Generated by gencpp from file kronton_serv/compleX.msg
// DO NOT EDIT!


#ifndef KRONTON_SERV_MESSAGE_COMPLEX_H
#define KRONTON_SERV_MESSAGE_COMPLEX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kronton_serv
{
template <class ContainerAllocator>
struct compleX_
{
  typedef compleX_<ContainerAllocator> Type;

  compleX_()
    : r(0.0)
    , i(0.0)  {
    }
  compleX_(const ContainerAllocator& _alloc)
    : r(0.0)
    , i(0.0)  {
  (void)_alloc;
    }



   typedef float _r_type;
  _r_type r;

   typedef float _i_type;
  _i_type i;





  typedef boost::shared_ptr< ::kronton_serv::compleX_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kronton_serv::compleX_<ContainerAllocator> const> ConstPtr;

}; // struct compleX_

typedef ::kronton_serv::compleX_<std::allocator<void> > compleX;

typedef boost::shared_ptr< ::kronton_serv::compleX > compleXPtr;
typedef boost::shared_ptr< ::kronton_serv::compleX const> compleXConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kronton_serv::compleX_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kronton_serv::compleX_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kronton_serv::compleX_<ContainerAllocator1> & lhs, const ::kronton_serv::compleX_<ContainerAllocator2> & rhs)
{
  return lhs.r == rhs.r &&
    lhs.i == rhs.i;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kronton_serv::compleX_<ContainerAllocator1> & lhs, const ::kronton_serv::compleX_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kronton_serv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kronton_serv::compleX_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kronton_serv::compleX_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kronton_serv::compleX_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kronton_serv::compleX_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kronton_serv::compleX_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kronton_serv::compleX_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kronton_serv::compleX_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f0be08c1f5d8c27359864de9d5522d0";
  }

  static const char* value(const ::kronton_serv::compleX_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f0be08c1f5d8c27ULL;
  static const uint64_t static_value2 = 0x359864de9d5522d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::kronton_serv::compleX_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kronton_serv/compleX";
  }

  static const char* value(const ::kronton_serv::compleX_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kronton_serv::compleX_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 r\n"
"float32 i\n"
;
  }

  static const char* value(const ::kronton_serv::compleX_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kronton_serv::compleX_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.i);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct compleX_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kronton_serv::compleX_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kronton_serv::compleX_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "i: ";
    Printer<float>::stream(s, indent + "  ", v.i);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRONTON_SERV_MESSAGE_COMPLEX_H
