// Generated by gencpp from file kronton_serv/countRequest.msg
// DO NOT EDIT!


#ifndef KRONTON_SERV_MESSAGE_COUNTREQUEST_H
#define KRONTON_SERV_MESSAGE_COUNTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kronton_serv
{
template <class ContainerAllocator>
struct countRequest_
{
  typedef countRequest_<ContainerAllocator> Type;

  countRequest_()
    : s()  {
    }
  countRequest_(const ContainerAllocator& _alloc)
    : s(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _s_type;
  _s_type s;





  typedef boost::shared_ptr< ::kronton_serv::countRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kronton_serv::countRequest_<ContainerAllocator> const> ConstPtr;

}; // struct countRequest_

typedef ::kronton_serv::countRequest_<std::allocator<void> > countRequest;

typedef boost::shared_ptr< ::kronton_serv::countRequest > countRequestPtr;
typedef boost::shared_ptr< ::kronton_serv::countRequest const> countRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kronton_serv::countRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kronton_serv::countRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kronton_serv::countRequest_<ContainerAllocator1> & lhs, const ::kronton_serv::countRequest_<ContainerAllocator2> & rhs)
{
  return lhs.s == rhs.s;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kronton_serv::countRequest_<ContainerAllocator1> & lhs, const ::kronton_serv::countRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kronton_serv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kronton_serv::countRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kronton_serv::countRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kronton_serv::countRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kronton_serv::countRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kronton_serv::countRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kronton_serv::countRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kronton_serv::countRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81af3411577d82a6786258523fc891ce";
  }

  static const char* value(const ::kronton_serv::countRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81af3411577d82a6ULL;
  static const uint64_t static_value2 = 0x786258523fc891ceULL;
};

template<class ContainerAllocator>
struct DataType< ::kronton_serv::countRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kronton_serv/countRequest";
  }

  static const char* value(const ::kronton_serv::countRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kronton_serv::countRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string s \n"
;
  }

  static const char* value(const ::kronton_serv::countRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kronton_serv::countRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct countRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kronton_serv::countRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kronton_serv::countRequest_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRONTON_SERV_MESSAGE_COUNTREQUEST_H
